### ISSUE TITLE
What about the capslock?

### ISSUE THREAD

**Issue by backdaniel** [tun/motospeed-ck61-backtick#1]
I don't use Xmonad, but I can do a similar thing in my WM... How do you use the capslock then?

**Comment by tun** [comment]
> I don't use Xmonad, but I can do a similar thing in my WM... How do you use the capslock then?

I use it as Escape key, since I use vim I found out more comfortable.

**Comment by backdaniel** [comment]
Ok so, when you press **CapsLock** in your keyboard its Esc and when you press **Escape** in your keyboard its backticks and tilde _and capslock_?

**Comment by tun** [comment]
> Ok so, when you press **CapsLock** in your keyboard its Esc and when you press **Escape** in your keyboard its backticks and tilde _and capslock_?

I don't have CapsLock at all, I use shift key if I need to uppercase chars.
